#!/usr/bin/env bash

# Multi monitor support. Needs MONITOR environment variable to be set for each instance of polybar
# If MONITOR environment variable is not set this will default to monitor 0
# Check https://github.com/polybar/polybar/issues/763
MON_IDX="0"
# mapfile -t MONITOR_LIST < <(polybar --list-monitors | cut -d":" -f1)
# for (( i=0; i<$((${#MONITOR_LIST[@]})); i++ )); do
#   [[ ${MONITOR_LIST[${i}]} == "$MONITOR" ]] && MON_IDX="$i"
# done;

herbstclient --idle "tag_*" 2>/dev/null | {

  while true; do
    # Read tags into $tags as array
    IFS=$'\t' read -ra tags <<< "$(herbstclient tag_status "${MON_IDX}")"
    {
      echo "(box :class \"workspace\"  :orientation \"h\" :spacing 5 :space-evenly \"false\" :truncate false"
      for i in "${tags[@]}" ; do
	# Read the prefix from each tag and render them according to that prefix
        tag="${i:1}"
        label="(label :text \"$tag\" :show-truncated \"false\")"
	case ${i:0:1} in
	  '.')
	    # the tag is empty
	    # TODO Add your formatting tags
	    # echo "%{F#345F0C} 0%{F-}"
	    # echo "%{A1:herbstclient focus_monitor ${MON_IDX}; herbstclient use ${i:1}:}%{B#345F0C}  ${i:1}  %{B-}%{A}"
	    ;;
	  ':')
	    # echo "%{A1:herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}:}%{F#608B4E} ${tag} %{F-}%{A}"
	    # echo  "(box :class \"works\"  :orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}\" :class  \"011\" \"$tag\") (button :onclick \"bspc desktop -f $ws2\"	:class \"011\"	\"2\") (button :onclick \"bspc desktop -f $ws3\"  :class \"0\" \"two\") (button :onclick \"bspc desktop -f $ws4\" :class \"033\"  \"third\") (button :onclick \"bspc desktop -f $ws5\"	:class \"03\" \"fourth\")  (button :onclick \"bspc desktop -f $ws6\"  :class \"0\" \"fifth\"))"
            echo  "(button :onclick \"herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}\" :class  \"tag_opened\" $label)"
	    ;;
	  '+')
	    # the tag is viewed on the specified MONITOR, but this monitor is not focused.
	    # TODO Add your formatting tags
	    ;;
	  '#')
	    # echo "%{A1:herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}:}%{F#569CD6} ${tag} %{F-}%{A}"
	    # echo  "(button :onclick \"bspc desktop -f $ws2\"  :class \"011\"  \"2\")"
	    echo  "(button :onclick \"herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}\" :class  \"tag_current\" $label)"
	    ;;
	  '-')
	    # the tag is viewed on a different MONITOR, but this monitor is not focused.
	    # TODO Add your formatting tags
	    ;;
	  '%')
	    # the tag is viewed on a different MONITOR and it is focused.
	    # TODO Add your formatting tags
	    ;;
	  '!')
	    tag="${i:1}"
	    echo  "(button :onclick \"herbstclient focus_monitor ${MON_IDX}; herbstclient use ${tag}\" :class  \"tag_urgent\" $label)"
	    ;;
	esac

      # focus the monitor of the current bar before switching tags
      # echo "%{A1:herbstclient focus_monitor ${MON_IDX}; herbstclient use ${i:1}:}  ${i:1}  %{A -u -o F- B-}"
      done
      echo " )"

      # reset foreground and background color to default
      # echo "%{F-}%{B-}"
    } | tr -d "\n"

    echo

    # wait for next event from herbstclient --idle
    read -r || break

  done

} 2>/dev/null
