dotfiles:
    - d_config_alacritty
    - d_config_bash
    - d_config_bat
    - d_config_bottom
    - d_config_conky
    - d_config_dotdrop
    - d_config_dunst
    - d_config_flameshot
    - d_config_fzfnova
    - d_config_git
    - d_config_herbstluftwm
    - d_config_i3
    - d_config_jgmenu
    - d_config_mpd
    - d_config_mycronjobs
    - d_config_neofetch
    - d_config_nnn
    - d_config_picom
    - d_config_polybar
    - d_config_eww
    - d_config_rofi
    - f_config_stalonetrayrc
    - d_config_starshipprompt
    - d_config_suckless
    - d_config_sway-launcher-desktop
    - d_config_sxhkd
    - d_config_tint2
    - d_config_tmux
    - d_config_vifm
    - d_config_wezterm
    - d_config_xfce4
    - d_config_zathura
    - d_config_zsh
