#!/usr/bin/env bash
killall conky

# Wait until the processes have been shut down
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done

conky -q -c ~/.config/conky/Mine/branch/left/conkyrc &
conky -q -c ~/.config/conky/Mine/branch/right/conkyrc &
exit
