#!/bin/bash

## Files and cmd
# FILE="$HOME/.cache/eww_launch.xyz"
# EWW="$HOME/.local/bin/eww/eww -c $HOME/.config/eww/bar"
EWW="eww -c $HOME/.config/eww/bar"

killall -q eww
while pgrep -u $UID -x eww >/dev/null; do sleep 1; done
${EWW} daemon

## Run eww daemon if not running already
# if [[ ! `pidof eww` ]]; then
#   ${EWW} daemon
#   sleep 1
# fi

## Open widgets
run_eww() {
  # ${EWW} open bar
  ${EWW} open bar_left
  ${EWW} open bar_center
  ${EWW} open bar_right
}
run_eww

# ## Launch or close widgets accordingly
# if [[ ! -f "$FILE" ]]; then
#   touch "$FILE"
#   run_eww
# else
#   ${EWW} close-all && killall eww
#   rm "$FILE"
# fi
