[colors.bright]
black = "#424242"
blue = "#8DA3B9"
# cream = "#928374"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.normal]
black = "#151515"
blue = "#8DA3B9"
# cream = "#786b53"
cyan = "#8AA6A2"
green = "#8CC77D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.primary]
background = "#151515"
foreground = "#E8E3E3"
