[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1.00"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2

[terminal]
