#!/usr/bin/env bash

#vifm preview dependency scripts
if [ -n "$INSIDE_VIFM" ]; then
    PS1="[Vi]$PS1"
    unset INSIDE_VIFM
fi

VIFM_VF_PATH="$HOME/.local/bin/vfcd"
if [[ -f "${VIFM_VF_PATH}" ]] ; then
    alias vf="source ${VIFM_VF_PATH}"
else
    alias vf=vifm
fi
